version: '2'
services:
  sqlserver:
    image: mssql-server
    environment:
        ACCEPT_EULA: Y
        SA_PASSWORD: 'password'
    ports:
        - "1433:1433"
  web:
    build: .
    ports:
        - "5000:5000"
    depends_on:
      - sqlserver
