version: '2'
services:
  sql:
    image: sqlserver:2016
    environment:
      SA_PASSWORD: "Bar123"
    ports:
      - "1433:1433" # for debug. Remove this for production
    tty: true

  musicstore:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "sql"
    ports:
      - "5000:5000"
    tty: true

networks:
  default:
    external:
      name: nat